name: fastapi-template 

services:
  api:
    image: cmtabr/fastapi-template:1.0.0
    container_name: backend
    build:
      context: api
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    watch:
      - action: sync
        path: ./api
        target: /src/api
